[package]
name = "wasmtime_bindings"
version = "0.1.0"
edition = "2021"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cxx = { version = "1.0.73", features = ["c++20"] }
wasmtime-wasi = "1.0.0"
futures = "0.3.23"
anyhow = "1.0.62"

[dependencies.wasmtime]
version = "1.0.0"
default-features = false
features = ["async", "wat", "cranelift"]
